// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IDestinationFile is an autogenerated mock type for the IDestinationFile type
type IDestinationFile struct {
	mock.Mock
}

type IDestinationFile_Expecter struct {
	mock *mock.Mock
}

func (_m *IDestinationFile) EXPECT() *IDestinationFile_Expecter {
	return &IDestinationFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *IDestinationFile) Close() {
	_m.Called()
}

// IDestinationFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IDestinationFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IDestinationFile_Expecter) Close() *IDestinationFile_Close_Call {
	return &IDestinationFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IDestinationFile_Close_Call) Run(run func()) *IDestinationFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDestinationFile_Close_Call) Return() *IDestinationFile_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *IDestinationFile_Close_Call) RunAndReturn(run func()) *IDestinationFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Limit provides a mock function with given fields:
func (_m *IDestinationFile) Limit() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Limit")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// IDestinationFile_Limit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Limit'
type IDestinationFile_Limit_Call struct {
	*mock.Call
}

// Limit is a helper method to define mock.On call
func (_e *IDestinationFile_Expecter) Limit() *IDestinationFile_Limit_Call {
	return &IDestinationFile_Limit_Call{Call: _e.mock.On("Limit")}
}

func (_c *IDestinationFile_Limit_Call) Run(run func()) *IDestinationFile_Limit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDestinationFile_Limit_Call) Return(_a0 int) *IDestinationFile_Limit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDestinationFile_Limit_Call) RunAndReturn(run func() int) *IDestinationFile_Limit_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields:
func (_m *IDestinationFile) Remove() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IDestinationFile_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type IDestinationFile_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
func (_e *IDestinationFile_Expecter) Remove() *IDestinationFile_Remove_Call {
	return &IDestinationFile_Remove_Call{Call: _e.mock.On("Remove")}
}

func (_c *IDestinationFile_Remove_Call) Run(run func()) *IDestinationFile_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IDestinationFile_Remove_Call) Return(_a0 error) *IDestinationFile_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IDestinationFile_Remove_Call) RunAndReturn(run func() error) *IDestinationFile_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: p
func (_m *IDestinationFile) Write(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IDestinationFile_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type IDestinationFile_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p []byte
func (_e *IDestinationFile_Expecter) Write(p interface{}) *IDestinationFile_Write_Call {
	return &IDestinationFile_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *IDestinationFile_Write_Call) Run(run func(p []byte)) *IDestinationFile_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *IDestinationFile_Write_Call) Return(n int, err error) *IDestinationFile_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *IDestinationFile_Write_Call) RunAndReturn(run func([]byte) (int, error)) *IDestinationFile_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewIDestinationFile creates a new instance of IDestinationFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDestinationFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDestinationFile {
	mock := &IDestinationFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
