// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ISourceFile is an autogenerated mock type for the ISourceFile type
type ISourceFile struct {
	mock.Mock
}

type ISourceFile_Expecter struct {
	mock *mock.Mock
}

func (_m *ISourceFile) EXPECT() *ISourceFile_Expecter {
	return &ISourceFile_Expecter{mock: &_m.Mock}
}

// CheckOffset provides a mock function with given fields:
func (_m *ISourceFile) CheckOffset() {
	_m.Called()
}

// ISourceFile_CheckOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOffset'
type ISourceFile_CheckOffset_Call struct {
	*mock.Call
}

// CheckOffset is a helper method to define mock.On call
func (_e *ISourceFile_Expecter) CheckOffset() *ISourceFile_CheckOffset_Call {
	return &ISourceFile_CheckOffset_Call{Call: _e.mock.On("CheckOffset")}
}

func (_c *ISourceFile_CheckOffset_Call) Run(run func()) *ISourceFile_CheckOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ISourceFile_CheckOffset_Call) Return() *ISourceFile_CheckOffset_Call {
	_c.Call.Return()
	return _c
}

func (_c *ISourceFile_CheckOffset_Call) RunAndReturn(run func()) *ISourceFile_CheckOffset_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *ISourceFile) Close() {
	_m.Called()
}

// ISourceFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ISourceFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ISourceFile_Expecter) Close() *ISourceFile_Close_Call {
	return &ISourceFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ISourceFile_Close_Call) Run(run func()) *ISourceFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ISourceFile_Close_Call) Return() *ISourceFile_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *ISourceFile_Close_Call) RunAndReturn(run func()) *ISourceFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: p
func (_m *ISourceFile) Read(p []byte) (int, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISourceFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type ISourceFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - p []byte
func (_e *ISourceFile_Expecter) Read(p interface{}) *ISourceFile_Read_Call {
	return &ISourceFile_Read_Call{Call: _e.mock.On("Read", p)}
}

func (_c *ISourceFile_Read_Call) Run(run func(p []byte)) *ISourceFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *ISourceFile_Read_Call) Return(n int, err error) *ISourceFile_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *ISourceFile_Read_Call) RunAndReturn(run func([]byte) (int, error)) *ISourceFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with given fields:
func (_m *ISourceFile) Size() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// ISourceFile_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type ISourceFile_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *ISourceFile_Expecter) Size() *ISourceFile_Size_Call {
	return &ISourceFile_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *ISourceFile_Size_Call) Run(run func()) *ISourceFile_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ISourceFile_Size_Call) Return(_a0 int) *ISourceFile_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISourceFile_Size_Call) RunAndReturn(run func() int) *ISourceFile_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewISourceFile creates a new instance of ISourceFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISourceFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISourceFile {
	mock := &ISourceFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
